import React, { useCallback, useMemo, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, ActivityIndicator, Alert } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { CatMood, moodEmojis, moodLabels, DiaryEntry } from '../types';
import { getRepository } from '../repositories';
import { calculateStreak } from '../storage/diaryStorage';
import { exportDiaryData, importDiaryData } from '../utils/export';
import { useTheme } from '../contexts/ThemeContext';
import { spacing, borderRadius, ThemeColors } from '../constants/theme';

const repository = getRepository();
const moods: CatMood[] = ['happy', 'sleepy', 'playful', 'hungry', 'relaxed'];

export default function StatsScreen() {
  const { colors } = useTheme(); const styles = useMemo(() => createStyles(colors), [colors]);
  const [entries, setEntries] = useState<DiaryEntry[]>([]); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [importing, setImporting] = useState(false);
  const loadEntries = useCallback(async (active: () => boolean = () => true) => { const data = await repository.getDiaryEntries(); if (!active()) return; setEntries(data); setLoading(false); }, []);
  useFocusEffect(useCallback(() => { let active = true; loadEntries(() => active); return () => { active = false; }; }, [loadEntries]));
  async function handleExport() { setExporting(true); try { await exportDiaryData(); } catch { Alert.alert('エラー', 'エクスポートに失敗しました'); } finally { setExporting(false); } }
  async function handleImport() { setImporting(true); try { const result = await importDiaryData(); if (result.success) { Alert.alert('インポート完了', `${result.imported}件をインポートしました${result.skipped ? `\n${result.skipped}件は既存データのためスキップ` : ''}`); await loadEntries(); } else if (result.error) Alert.alert('エラー', result.error); } catch { Alert.alert('エラー', 'インポートに失敗しました'); } finally { setImporting(false); } }
  const counts = moods.reduce((acc, mood) => ({ ...acc, [mood]: entries.filter((e) => e.mood === mood).length }), {} as Record<CatMood, number>);
  const mostCommon = entries.length ? moods.reduce((a, b) => counts[a] >= counts[b] ? a : b) : null;
  if (loading) return <View style={styles.loading}><ActivityIndicator size="large" color={colors.primary} /></View>;
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}><View style={styles.summary}><Text style={styles.emoji}>📊</Text><Text style={styles.title}>日記の統計</Text><View style={styles.streak}><Text style={styles.streakText}>🔥 {calculateStreak(entries)}日連続</Text></View><View style={styles.row}><Metric value={entries.length} label="総日記数" styles={styles} /><Metric value={entries.filter((e) => e.photoUri).length} label="写真付き" styles={styles} /></View>{mostCommon && <Text style={styles.common}>よくある気分: {moodEmojis[mostCommon]} {moodLabels[mostCommon]}</Text>}</View><Text style={styles.sectionTitle}>気分の分布</Text>{moods.map((mood) => { const pct = entries.length ? counts[mood] / entries.length * 100 : 0; return <View key={mood} style={styles.moodRow}><Text style={styles.moodEmoji}>{moodEmojis[mood]}</Text><View style={styles.barBg}><View style={[styles.bar, { width: `${pct}%` }]} /></View><Text style={styles.count}>{counts[mood]}</Text></View>; })}<View style={styles.buttons}><TouchableOpacity style={styles.button} onPress={handleExport} disabled={exporting}>{exporting ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>📤 完全バックアップ</Text>}</TouchableOpacity><TouchableOpacity style={[styles.button, styles.secondary]} onPress={handleImport} disabled={importing}>{importing ? <ActivityIndicator color="#fff" /> : <Text style={styles.buttonText}>📥 復元</Text>}</TouchableOpacity></View></ScrollView>;
}
function Metric({ value, label, styles }: { value: number; label: string; styles: ReturnType<typeof createStyles> }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
const createStyles = (colors: ThemeColors) => StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, loading: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: colors.background }, content: { padding: spacing.xl }, summary: { backgroundColor: colors.card, borderRadius: borderRadius.lg, padding: spacing.xl, alignItems: 'center', marginBottom: spacing.xl }, emoji: { fontSize: 44 }, title: { fontSize: 20, fontWeight: 'bold', color: colors.text, marginVertical: spacing.md }, streak: { backgroundColor: colors.primary, borderRadius: borderRadius.full, paddingHorizontal: spacing.lg, paddingVertical: spacing.sm, marginBottom: spacing.lg }, streakText: { color: '#fff', fontWeight: 'bold' }, row: { flexDirection: 'row', width: '100%', justifyContent: 'space-around' }, metric: { alignItems: 'center' }, metricValue: { color: colors.primary, fontSize: 34, fontWeight: 'bold' }, metricLabel: { color: colors.textSecondary }, common: { color: colors.textSecondary, marginTop: spacing.lg }, sectionTitle: { color: colors.text, fontWeight: 'bold', fontSize: 18, marginBottom: spacing.md }, moodRow: { flexDirection: 'row', alignItems: 'center', marginBottom: spacing.md }, moodEmoji: { width: 36, fontSize: 24 }, barBg: { flex: 1, height: 18, backgroundColor: colors.backgroundMuted, borderRadius: 9, overflow: 'hidden' }, bar: { height: '100%', backgroundColor: colors.primary }, count: { width: 30, textAlign: 'right', color: colors.textSecondary }, buttons: { flexDirection: 'row', gap: spacing.md, marginTop: spacing.xl }, button: { flex: 1, backgroundColor: colors.primary, borderRadius: borderRadius.md, padding: spacing.lg, alignItems: 'center' }, secondary: { backgroundColor: colors.textSecondary }, buttonText: { color: '#fff', fontWeight: 'bold' } });
